import { chromium } from 'playwright-core';
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--enable-unsafe-webgpu'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 900 } });
const logs = [];
page.on('console', (m) => logs.push(`[${m.type()}] ${m.text()}`));
page.on('pageerror', (e) => logs.push(`[pageerror] ${e.message}`));
await page.goto('http://127.0.0.1:5291/?warm=8');
await page.waitForFunction(() => window.__ready === true, null, { timeout: 120000 });
await page.waitForTimeout(1500);
await page.mouse.move(250, 560);
await page.mouse.down();
await page.mouse.move(800, 760, { steps: 8 });
await page.mouse.move(1500, 880, { steps: 8 });
await page.screenshot({ path: 'shots/i01_drag.png' });
await page.mouse.up();
await page.waitForTimeout(400);
const selected = await page.evaluate(() => [...window.__engine.views.selected]);
await page.keyboard.press('Digit1');
await page.waitForTimeout(2500);
await page.screenshot({ path: 'shots/i02_crane.png' });
await page.mouse.click(900, 500, { button: 'right' });
await page.waitForTimeout(1200);
const orders = await page.evaluate(() => window.__engine.battle.ships.filter((s) => window.__engine.views.selected.has(s.id)).map((s) => s.order.type));
console.log('selected', JSON.stringify(selected), 'orders', JSON.stringify(orders));
await page.screenshot({ path: 'shots/i03_move.png' });
console.log(logs.filter((l) => !l.includes('Clock') && !l.includes('powerPreference') && !l.includes('vite') && !l.includes('DevTools')).slice(-10).join('\n'));
await browser.close();
