import type { GunSpec, GunType, ShipKind, ShipSpec } from './types';

export const STAGE_NAMES = ['포구 청소', '화약 장전', '격목 다짐', '탄환 장전', '조준', '점화'];

export const GUN_SHOTS: Record<GunType, number> = { cheonja: 18, jija: 24, hyeonja: 36, hwangja: 48, seungja: 60, ozutsu: 30, folangji: 50, hudun: 40 };

export const NO_MODS = { reload: 1, accuracy: 1, speed: 1, turn: 1, fire: 1, melee: 1, defense: 1 };

export const GUN_SPECS: Record<GunType, GunSpec> = {
  cheonja: {
    type: 'cheonja',
    label: '천자총통',
    hanja: '天字銃筒',
    range: 520,
    damage: 15,
    crewDamage: 5,
    muzzle: 150,
    stages: [9, 14, 8, 12, 6, 1.2],
    ammo: 'arrow',
    big: true,
  },
  jija: {
    type: 'jija',
    label: '지자총통',
    hanja: '地字銃筒',
    range: 460,
    damage: 10,
    crewDamage: 4,
    muzzle: 140,
    stages: [7, 11, 6, 9, 5, 1],
    ammo: 'arrow',
    big: true,
  },
  hyeonja: {
    type: 'hyeonja',
    label: '현자총통',
    hanja: '玄字銃筒',
    range: 400,
    damage: 6,
    crewDamage: 6,
    muzzle: 135,
    stages: [5, 8, 4, 6, 4, 0.8],
    ammo: 'ball',
    big: false,
  },
  hwangja: {
    type: 'hwangja',
    label: '황자총통',
    hanja: '黃字銃筒',
    range: 360,
    damage: 3.5,
    crewDamage: 7,
    muzzle: 130,
    stages: [3, 5, 3, 4, 3, 0.6],
    ammo: 'grape',
    big: false,
  },
  seungja: {
    type: 'seungja',
    label: '승자총통',
    hanja: '勝字銃筒',
    range: 160,
    damage: 0.8,
    crewDamage: 4,
    muzzle: 120,
    stages: [2, 3, 2, 2, 2, 0.4],
    ammo: 'ball',
    big: false,
  },
  folangji: {
    type: 'folangji',
    label: '불랑기포',
    hanja: '佛郎機砲',
    range: 400,
    damage: 7,
    crewDamage: 5,
    muzzle: 150,
    stages: [2, 4, 1.5, 3, 3, 0.7],
    ammo: 'ball',
    big: false,
  },
  hudun: {
    type: 'hudun',
    label: '호준포',
    hanja: '虎蹲砲',
    range: 220,
    damage: 2.5,
    crewDamage: 8,
    muzzle: 120,
    stages: [3, 4, 2, 3, 2, 0.6],
    ammo: 'grape',
    big: false,
  },
  ozutsu: {
    type: 'ozutsu',
    label: '대통',
    hanja: '大筒',
    range: 230,
    damage: 4,
    crewDamage: 5,
    muzzle: 120,
    stages: [5, 8, 4, 6, 4, 0.8],
    ammo: 'ball',
    big: false,
  },
};

const sides = (gun: GunType, count: number) => [
  { gun, count, side: 0 as const },
  { gun, count, side: 1 as const },
];

export const SHIP_SPECS: Record<ShipKind, ShipSpec> = {
  panokseon: {
    kind: 'panokseon',
    faction: 'joseon',
    label: '판옥선',
    team: 'joseon',
    length: 40,
    beam: 11.5,
    deck: 5.5,
    height: 19,
    maxSpeed: 5.2,
    accel: 0.5,
    turnRate: 0.19,
    hull: 140,
    crew: 160,
    batteries: [...sides('cheonja', 1), ...sides('jija', 2), ...sides('hyeonja', 2), ...sides('hwangja', 2)],
    musketRange: 0,
    musketPower: 0,
    melee: 1,
    deckDefense: 1.8,
    armor: 0.18,
    boardable: true,
    ramPower: 1.1,
    soldiers: 26,
  },
  geobukseon: {
    kind: 'geobukseon',
    faction: 'joseon',
    label: '거북선',
    team: 'joseon',
    length: 32,
    beam: 9,
    deck: 3.8,
    height: 7,
    maxSpeed: 5.8,
    accel: 0.65,
    turnRate: 0.21,
    hull: 170,
    crew: 140,
    batteries: [{ gun: 'hyeonja', count: 1, side: 2 }, ...sides('jija', 1), ...sides('hyeonja', 2), ...sides('hwangja', 2)],
    musketRange: 0,
    musketPower: 0,
    melee: 1.2,
    deckDefense: 3,
    armor: 0.45,
    boardable: false,
    ramPower: 2.6,
    soldiers: 0,
  },
  hyeopseon: {
    kind: 'hyeopseon',
    faction: 'joseon',
    label: '협선',
    team: 'joseon',
    length: 13,
    beam: 3.6,
    deck: 1.6,
    height: 7,
    maxSpeed: 6.4,
    accel: 0.9,
    turnRate: 0.32,
    hull: 32,
    crew: 22,
    batteries: [...sides('seungja', 1)],
    musketRange: 0,
    musketPower: 0,
    melee: 0.9,
    deckDefense: 1,
    armor: 0.03,
    boardable: true,
    ramPower: 0.4,
    soldiers: 6,
  },
  atakebune: {
    kind: 'atakebune',
    faction: 'japan',
    label: '대선 (아타케부네)',
    team: 'japan',
    length: 40,
    beam: 12.5,
    deck: 5,
    height: 18,
    maxSpeed: 4.3,
    accel: 0.35,
    turnRate: 0.1,
    hull: 230,
    crew: 260,
    batteries: [...sides('ozutsu', 2)],
    musketRange: 150,
    musketPower: 1.35,
    melee: 1,
    deckDefense: 1.3,
    armor: 0.2,
    boardable: true,
    ramPower: 1.5,
    soldiers: 30,
  },
  sekibune: {
    kind: 'sekibune',
    faction: 'japan',
    label: '중선 (세키부네)',
    team: 'japan',
    length: 24,
    beam: 6,
    deck: 2.9,
    height: 9,
    maxSpeed: 7,
    accel: 0.8,
    turnRate: 0.27,
    hull: 85,
    crew: 80,
    batteries: [],
    musketRange: 125,
    musketPower: 0.85,
    melee: 1,
    deckDefense: 1,
    armor: 0.06,
    boardable: true,
    ramPower: 0.8,
    soldiers: 14,
  },
  kobaya: {
    kind: 'kobaya',
    faction: 'japan',
    label: '소선 (고바야)',
    team: 'japan',
    length: 13,
    beam: 3,
    deck: 1.5,
    height: 7,
    maxSpeed: 7.6,
    accel: 1,
    turnRate: 0.34,
    hull: 34,
    crew: 32,
    batteries: [],
    musketRange: 110,
    musketPower: 0.4,
    melee: 1,
    deckDefense: 0.9,
    armor: 0.02,
    boardable: true,
    ramPower: 0.4,
    soldiers: 7,
  },
  mingship: {
    kind: 'mingship',
    faction: 'ming',
    label: '명 전선 (복선)',
    team: 'joseon',
    length: 36,
    beam: 10,
    deck: 6,
    height: 22,
    maxSpeed: 4.4,
    accel: 0.38,
    turnRate: 0.14,
    hull: 170,
    crew: 200,
    batteries: [...sides('folangji', 3), ...sides('hudun', 1)],
    musketRange: 130,
    musketPower: 0.7,
    melee: 1.05,
    deckDefense: 1.5,
    armor: 0.15,
    boardable: true,
    ramPower: 1.2,
    soldiers: 28,
  },
  mingsmall: {
    kind: 'mingsmall',
    faction: 'ming',
    label: '명 사선',
    team: 'joseon',
    length: 18,
    beam: 5,
    deck: 2.6,
    height: 12,
    maxSpeed: 6,
    accel: 0.7,
    turnRate: 0.26,
    hull: 60,
    crew: 60,
    batteries: [...sides('folangji', 1)],
    musketRange: 110,
    musketPower: 0.5,
    melee: 1,
    deckDefense: 1,
    armor: 0.05,
    boardable: true,
    ramPower: 0.6,
    soldiers: 10,
  },
};
